import cors from 'cors';
import express from 'express';
import bodyParser from 'body-parser';
import routes from './routes.js';
import errorMiddleware from '../middleware/error-middleware.js';
import jwt from 'jsonwebtoken';

const app = express()

app.use(bodyParser.json())
app.use(cors())

app.use(routes.apiRoutes);
app.use(errorMiddleware);

console.log(jwt.decode("eyJraWQiOiJGS2Q1K0xvMWd6bDNHNW1nUk5aUXRvbFVaQUZ1Z2ZZNVBKcFg3K1RCb1pNPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJkZWE0YWNkNS1iZjIyLTQ2ZTYtODY4Yy03NjI5ZmVmMTk5NDEiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuc2EtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3NhLWVhc3QtMV9xQ1I5SHh2bkciLCJjbGllbnRfaWQiOiIyaGVscDB1NGw0a2pvOHAxYWEwNGZsOW1rcCIsIm9yaWdpbl9qdGkiOiIxYWM1YjlmMC04MzQwLTQzZTktYTM5Mi05ZTM3ODY4NTk5ZjciLCJldmVudF9pZCI6IjhiNjM3MjVmLTVkMmMtNDdjNy1hMDA0LWYxOWRiNWUyMTJmMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NzU3ODAwNDgsImV4cCI6MTY3NTc4MzY0OCwiaWF0IjoxNjc1NzgwMDQ4LCJqdGkiOiIyNjIyODRjNi1lZDJmLTQ0YTQtODcxNC0xYzEyZWUzOWRhYjIiLCJ1c2VybmFtZSI6ImRlYTRhY2Q1LWJmMjItNDZlNi04NjhjLTc2MjlmZWYxOTk0MSJ9.anr3U1nLbynQeZ3lddBKMRUzuzHj0dAS3mSzbWAYkZfw-jP18dGpgGP66SvkaNfkn17l4zbLNp82pv5ZscZGhIfipb2z8RaOU3ICmRhthAWnUjt7TtaacEFqghFwGOMH7Ycm_zgFN0e-r_kD3ZHNvt0XRtuJUGXft1JShMUFy7_n714_-GE60wgvSpjxQS9NjgOVoAJChs1CX3d3qOee_qgUXh8C73UNnGZcyZMZRGs_zptEsd3SilTxTJQI-WUAi5jk-muPr7aodb2mwoqLFuHpdBT5e-IUPcSNaTcD2DcxsTaUtIfOLWUoNxH5zMbJncMZutra7oG41B6nAsmk0w", { complete: true }));

export default app;