# Serverless Infrastucture to APIs used in Rancheiros MC
# Doc: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Configure a Development Serverless Infrastructure in AWS

Parameters:
  StageName:
    Type: String
    Description: API Stage name
    Default: dev
  DevCognitoUserPoolName:
    Type: String
    Description: User pool name
    Default: rancheiros-dev
  ClientDevCognitoUserPoolName:
    Type: String
    Description: Client user pool name
    Default: rancheiros-dev-client

# Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # LogicalID
  ApiGatewayDevApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub rancheiros-api-${StageName}
      Description: "Define a API Gateway to Development env"
      StageName: !Ref StageName
      # Cors only works to inline functions
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,limit,page,access_token,id_token,filter'"
        AllowOrigin: "'*'"
        MaxAge: "'5'"
        AllowCredentials: false
      # Auth:
      #   DefaultAuthorizer: DevCognitoAuthorizer
      #   Authorizers:
      #     DevCognitoAuthorizer:
      #       UserPoolArn: !GetAtt DevCognitoUserPool.Arn

  HelloDevLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello from Rancheiros MC API!', 'statusCode': 200}
      Events:
        HelloDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /status
            Method: GET

  DataClassDevDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub rancheiros-table-${StageName}-class
      AttributeDefinitions: 
        - 
          AttributeName: "city"
          AttributeType: "S"
        - 
          AttributeName: "date"
          AttributeType: "S"
        - 
          AttributeName: "active"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "city"
          KeyType: "HASH"
        - 
          AttributeName: "date"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - 
          IndexName: Active
          KeySchema: 
            - 
              AttributeName: "active"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  DataUserDevDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub rancheiros-table-${StageName}-user
      AttributeDefinitions: 
        - 
          AttributeName: "driver_license_UF"
          AttributeType: "S"
        - 
          AttributeName: "driver_license"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "driver_license_UF"
          KeyType: "HASH"
        - 
          AttributeName: "driver_license"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  DataEnrollDevDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub rancheiros-table-${StageName}-enroll
      AttributeDefinitions: 
        - 
          AttributeName: "city"
          AttributeType: "S"
        - 
          AttributeName: "enroll_date"
          AttributeType: "S"
        - 
          AttributeName: "class"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "city"
          KeyType: "HASH"
        - 
          AttributeName: "enroll_date"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - 
          IndexName: Class
          KeySchema: 
            - 
              AttributeName: "class"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  ServerlessDevLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./node-js
      Handler: ./src/serverless.handler
      MemorySize: 1024
      Runtime: nodejs16.x
      Timeout: 30
      Events:
        ServerProxyManagerDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /manager/{proxy+}
            Method: POST
        ServerProxyManagerPutDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /manager/{proxy+}
            Method: PUT
        ServerProxyEnrollDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /enroll
            Method: POST
        ServerProxyReportDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /report/{proxy+}
            Method: GET
        ServerProxyLoginDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /login
            Method: POST
        ServerProxyClassPostDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /class
            Method: POST
        ServerProxyClassGetDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /class
            Method: GET
        ServerProxyClassGetProxyDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /class/{proxy+}
            Method: GET
        ServerProxyLegacyDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /legacy
            Method: POST
        ListPhotosDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /photos
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataUserDevDynamoDb
        - DynamoDBCrudPolicy:
            TableName: !Ref DataEnrollDevDynamoDb
        - DynamoDBCrudPolicy:
            TableName: !Ref DataClassDevDynamoDb
      Environment:
        Variables:
          ENV: "development"
          TABLE_NAME: !Sub rancheiros-table-${StageName}
          CLIENT_ID: !Ref ClientDevCognitoUserPool
          USER_POOL_ID: !Ref DevCognitoUserPool

  DevCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref DevCognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: cities
          Mutable: true
        - AttributeDataType: String
          Name: enroll_status
          Mutable: true
        - AttributeDataType: String
          Name: manage_class
          Mutable: true
        - AttributeDataType: String
          Name: viewer
          Mutable: true
        - AttributeDataType: String
          Name: caller
          Mutable: true
        - AttributeDataType: String
          Name: download
          Mutable: true
        - AttributeDataType: String
          Name: manager
          Mutable: true
        - AttributeDataType: String
          Name: posclass
          Mutable: true

  ClientDevCognitoUserPool:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref DevCognitoUserPool
      ClientName: !Ref ClientDevCognitoUserPoolName
      GenerateSecret: false

Outputs:
  ApiUrl:
    Description:
      Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Sub https://${ApiGatewayDevApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/
