# Serverless Infrastucture to APIs used in Rancheiros MC
# Doc: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Configure a Production Serverless Infrastructure in AWS

Parameters:
  StageName:
    Type: String
    Description: API Stage name
    Default: prod
  ProdCognitoUserPoolName:
    Type: String
    Description: User pool name
    Default: rancheiros-prod
  ClientProdCognitoUserPoolName:
    Type: String
    Description: Client user pool name
    Default: rancheiros-prod-client

# Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # LogicalID
  ApiGatewayProdApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub rancheiros-api-${StageName}
      Description: "Define a API Gateway to production env"
      StageName: !Ref StageName
      # Cors only works to inline functions
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,limit,page,access_token,id_token,filter'"
        AllowOrigin: "'*'"
        MaxAge: "'5'"
        AllowCredentials: false
      # Auth:
      #   DefaultAuthorizer: ProdCognitoAuthorizer
      #   Authorizers:
      #     ProdCognitoAuthorizer:
      #       UserPoolArn: !GetAtt ProdCognitoUserPool.Arn

  HelloProdLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello from Rancheiros MC API!', 'statusCode': 200}
      Events:
        HelloProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /status
            Method: GET

  DataClassProdDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub rancheiros-table-${StageName}-class
      AttributeDefinitions: 
        - 
          AttributeName: "city"
          AttributeType: "S"
        - 
          AttributeName: "date"
          AttributeType: "S"
        - 
          AttributeName: "active"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "city"
          KeyType: "HASH"
        - 
          AttributeName: "date"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - 
          IndexName: Active
          KeySchema: 
            - 
              AttributeName: "active"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  DataUserProdDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub rancheiros-table-${StageName}-user
      AttributeDefinitions: 
        - 
          AttributeName: "driver_license_UF"
          AttributeType: "S"
        - 
          AttributeName: "driver_license"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "driver_license_UF"
          KeyType: "HASH"
        - 
          AttributeName: "driver_license"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  DataEnrollProdDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub rancheiros-table-${StageName}-enroll
      AttributeDefinitions: 
        - 
          AttributeName: "city"
          AttributeType: "S"
        - 
          AttributeName: "enroll_date"
          AttributeType: "S"
        - 
          AttributeName: "class"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "city"
          KeyType: "HASH"
        - 
          AttributeName: "enroll_date"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - 
          IndexName: Class
          KeySchema: 
            - 
              AttributeName: "class"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  ServerlessProdLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./node-js
      Handler: ./src/serverless.handler
      MemorySize: 1024
      Runtime: nodejs16.x
      Timeout: 30
      Events:
        ServerProxyManagerProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /manager/{proxy+}
            Method: POST
        ServerProxyManagerPutProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /manager/{proxy+}
            Method: PUT
        ServerProxyEnrollProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /enroll
            Method: POST
        ServerProxyReportProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /report/{proxy+}
            Method: GET
        ServerProxyLoginProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /login
            Method: POST
        ServerProxyClassPostProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /class
            Method: POST
        ServerProxyClassGetProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /class
            Method: GET
        ServerProxyClassGetProxyProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /class/{proxy+}
            Method: GET
        ServerProxyLegacyProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /legacy
            Method: POST
        ListPhotosProdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayProdApi
            Path: /photos
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataUserProdDynamoDb
        - DynamoDBCrudPolicy:
            TableName: !Ref DataEnrollProdDynamoDb
        - DynamoDBCrudPolicy:
            TableName: !Ref DataClassProdDynamoDb
      Environment:
        Variables:
          ENV: "development"
          TABLE_NAME: !Sub rancheiros-table-${StageName}
          CLIENT_ID: !Ref ClientProdCognitoUserPool
          USER_POOL_ID: !Ref ProdCognitoUserPool

  ProdCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref ProdCognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: cities
          Mutable: true
        - AttributeDataType: String
          Name: enroll_status
          Mutable: true
        - AttributeDataType: String
          Name: manage_class
          Mutable: true
        - AttributeDataType: String
          Name: viewer
          Mutable: true
        - AttributeDataType: String
          Name: caller
          Mutable: true
        - AttributeDataType: String
          Name: download
          Mutable: true
        - AttributeDataType: String
          Name: manager
          Mutable: true
        - AttributeDataType: String
          Name: posclass
          Mutable: true

  ClientProdCognitoUserPool:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ProdCognitoUserPool
      ClientName: !Ref ClientProdCognitoUserPoolName
      GenerateSecret: false

Outputs:
  ApiUrl:
    Description:
      Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Sub https://${ApiGatewayProdApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/
