# Serverless Infrastucture to PPV APIs
# Doc: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Configure a Development Serverless Infrastructure in AWS

Parameters:
  StageName:
    Type: String
    Description: API Stage name
    Default: dev
  DevCognitoUserPoolName:
    Type: String
    Description: User pool name
    Default: dev
  ClientDevCognitoUserPoolName:
    Type: String
    Description: Client user pool name
    Default: client_dev

# Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # LogicalID
  ApiGatewayDevApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ppv-api-${StageName}
      Description: "Define a API Gateway to Development env"
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,limit,page,access_token,id_token'"
        AllowOrigin: "'*'"
        MaxAge: "'5'"
        AllowCredentials: false
      # Auth:
      #   DefaultAuthorizer: DevCognitoAuthorizer
      #   Authorizers:
      #     DevCognitoAuthorizer:
      #       UserPoolArn: !GetAtt DevCognitoUserPool.Arn

  HelloDevLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'I am here!', 'statusCode': 200}
      Events:
        HelloDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /status
            Method: GET

  DataUserDevDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ppv-table-${StageName}-user
      AttributeDefinitions: 
        - 
          AttributeName: "driver_license_UF"
          AttributeType: "S"
        - 
          AttributeName: "driver_license"
          AttributeType: "S"
        - 
          AttributeName: "updated_by"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "driver_license_UF"
          KeyType: "HASH"
        - 
          AttributeName: "driver_license"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - 
          IndexName: UpdatedBy
          KeySchema: 
            - 
              AttributeName: "updated_by"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  DataEnrollDevDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ppv-table-${StageName}-enroll
      AttributeDefinitions: 
        - 
          AttributeName: "city"
          AttributeType: "S"
        - 
          AttributeName: "enroll_date"
          AttributeType: "S"
        - 
          AttributeName: "motorcycle_brand"
          AttributeType: "S"
        - 
          AttributeName: "motorcycle_model"
          AttributeType: "S"
        - 
          AttributeName: "motorcycle_use"
          AttributeType: "S"
        - 
          AttributeName: "enroll_status"
          AttributeType: "S"
        - 
          AttributeName: "updated_by"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "city"
          KeyType: "HASH"
        - 
          AttributeName: "enroll_date"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - 
          IndexName: UpdatedBy
          KeySchema: 
            - 
              AttributeName: "updated_by"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        - 
          IndexName: EnrollStatus
          KeySchema: 
            - 
              AttributeName: "enroll_status"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        - 
          IndexName: MotorcycleBrand
          KeySchema: 
            - 
              AttributeName: "motorcycle_brand"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "mototcycle_model"
              - "enroll_status"
              - "motorcycle_use"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        - 
          IndexName: MotorcycleUse
          KeySchema: 
            - 
              AttributeName: "motorcycle_use"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "motorcycle_model"
              - "enroll_status"
              - "motorcycle_brand"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        - 
          IndexName: MotorcycleUse
          KeySchema: 
            - 
              AttributeName: "motorcycle_model"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "mototcycle_use"
              - "enroll_status"
              - "motorcycle_brand"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  ServerlessDevLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./node-js
      Handler: ./src/serverless.handler
      MemorySize: 1024
      Runtime: nodejs16.x
      Timeout: 30
      Events:
        ServerProxyEnrollDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /enroll
            Method: POST
        ServerProxyReportDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /report/{proxy+}
            Method: GET
        ServerProxyLoginDevEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevApi
            Path: /login
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataUserDevDynamoDb
        - DynamoDBCrudPolicy:
            TableName: !Ref DataEnrollDevDynamoDb
      Environment:
        Variables:
          TABLE_NAME: !Sub ppv-table-${StageName}
          CLIENT_ID: !Ref ClientDevCognitoUserPool
          USER_POOL_ID: !Ref DevCognitoUserPool

  DevCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref DevCognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true

  ClientDevCognitoUserPool:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref DevCognitoUserPool
      ClientName: !Ref ClientDevCognitoUserPoolName
      GenerateSecret: false

Outputs:
  ApiUrl:
    Description:
      Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Sub https://${ApiGatewayDevApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/
